POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QiLCJpZCI6IjY5MDZlODY3NWYyZjZlZjExMDkyM2NlNCIsImlhdCI6MTc2MjA2MDQwOSwiZXhwIjoxNzYyMDY0MDA5fQ.1NI9d_BM1JromJZTjpC1E9y7HKlq0CEsZ9Ch56hVobs

{
  "content": "heyad",
  "important": true
}