DELETE http://localhost:3001/api/notes/6906e8faa7f36c1d32445ffb
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2OTA2ZTkxOWE3ZjM2YzFkMzI0NDYwMDAiLCJpYXQiOjE3NjIwNjA1ODYsImV4cCI6MTc2MjA2NDE4Nn0.yzrxhF_8MZ3sjj5SLhhKJyIeJyU9wFE7El4tuxYx_jg