POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample"
}
###
POST https://full-stack-open-1-6v06.onrender.com/api/persons HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number":"39-44-5323523"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "sample",
    "number":"39-44-5323523"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "hi",
    "number":"39-44-5323523"
}