POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample"
}
###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number":"39-44-5323523"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number":"39-44-5323523"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "hi",
    "number":"39-44-5323523"
}